### ISSUE TITLE
Project demonstration 1

### ISSUE THREAD

**Issue by Sneakycloud** [Sneakycloud/Priority-calculator#68] opened 2024-04-16 18:30 UTC
The purpose of this session is to talk about the project you have developed in two ways:

- project itself, how it works, implementation details, etc;
- how you are managing it with regards to the course content: CI/CD, Project Requirements, testing, etc.

In the first seminar, the focus will be on discussing the fundamentals covered in the first part of the course, including chapters 1-4 and 14 in the course book, [Continuous Delivery](https://primo.library.ju.se/discovery/fulldisplay?docid=alma998035797603831&context=L&vid=46JUL_INST:jul&tab=Everything):

- Configuration management
- Continuous Integration
- Testing Strategy
- Version Control

 

Note: All groups are expected to attend the demonstration. Each group have 10 minutes to present their project from a number of perspectives. You do not need to have any slides.

**Preparation Instructions**

Read the five chapters mentioned above. Each one in the group writes a short reflection (not more than one A4) on how the literature is applicable to your project and what insights they give on how to work in larger projects than this. End the reflection with one sentence per chapter describing the main take-away of that chapter. Post your reflections as comments to the issue created for this seminar. **Post the reflections no later than midnight the day before the seminar.**

**Comment by Sneakycloud** [comment] 2024-04-22 16:47
Delivering software comes with a myriad of problems but a significant part is caused by human error which makes the problems inconsistent and hard to discover. The authors of continuous integration regard the automation of the development,testing and deployment as of vital importance to delivering software which is consistent and reproducible. This rings true regardless of the project size but becomes a larger point of failure for larger projects.
This leads to the importance of configuration settings as they are as important as the source code itself but often go without any of the extensive tests that the code is exposed to. Configuration settings include the settings for the OS, third-party services and the application itself. A single misconfigured version for an external service or library could lead to unpredictable problems which are hard to reproduce and even harder to locate the cause. This is why automation is recommended as the scripts themselves serve as documentation for the exact configuration that the program was designed for without any room for misinterpretation. Putting these scripts and external libraries into version control also ensures that the settings are correctly configured for applications version which always makes reverting to older versions of the software reliable.
Continuous Integration (CI) supports automation by encouraging frequent commits, which helps catch errors early, minimizes merge conflicts and maintains a functional build throughout development. It also enforces the automated configuration settings which CI servers can use to build and test the changes allowing for a clear view of the current state of the project and if it can be deployed. This is very useful for all projects as it avoids “merge hell” which for larger projects can take weeks to complete and it can be discovered that different branches used different versions of third-party software.
Automated tests are another automatable and important aspect of development as they ensure that the project is not just buildable but fulfills the expected requirements. They allow developers and testers to save time and focus on more complex tasks. By writing acceptance tests with input from customers, developers can align their work with customer needs from the outset, reducing rework and keeping the project on track. These can then be used as a measure of how complete a project is.
Version control systems are a cornerstone of modern code development as they allow for features such as management of teams,branching and reverting. DVCS have the additional benefits of being able to function offline and being able to cherry pick commits which allows for a thriving open source community. For simple projects branching may not be too big of a deal but as they grow in size merge conflicts become an ever growing problem. This leads to different branch patterns like mainline development, branch by feature and branch by team with different pros and cons. It is always a trade off between code management and parallel coding in opposition to using the practices of CI.

Chapter takeaways:

1. Automating the software development processes makes it cheaper, better quality and faster to develop and avoids bugs creeping into production.
2. Managing configuration settings is as important as managing the source code.
3. Push and pull regularly to prevent large merge conflicts but do not push a broken build.
4. Tests should be thoroughly integrated with the development process from start to finish.
14. Always consider the cost of branching before doing it.

**Comment by ebbabrage** [comment] 2024-04-22 18:46
It is very important to implement testing and well written documentation early in the process. This is important because regular testing will help find errors and problems in earlier stages and with documentation it is easier to find where the errors may have occurred. In our project the implementation of testing helps detect errors before we merge into the main code. We also have a better workflow due to the documentation. It is clear what everyone does, what has to be done and backtrack what has been done if any questions occur. In a bigger organization and projects these principles become of even more importance due to time efficiencies and bigger costs. Releases also become more reliable when every step of the projects is carefully handled, tested and documented. A key to this is atomization.  

Atomization is also a key when it comes to configuration. A continuous configuration together with well written documentation will in many cases (if not all) save a lot of time and money. Configuration information for the applications and environment is preferably supplied in the organization through the same mechanism. To ensure that references to external services setting are good and to run some soke test on the applications are two ways to test the configurations. Besides atomization is to keep all configuration information in one place and to keep binary files independent two keys to better and more effective configuration.  

To ensure that a project always has its application in a working state CI is used. CI helps productivity and makes it easier to detect issues in an earlier state and therefore is a cost-efficient resolution. It is easier to see the benefits of using CI in bigger projects where it is crucial to implement CI to maintain the quality of the project at all times. It's important for us in our project and in bigger projects to integrate CI in the workflow to ensure successful projects. 

To achieve high-quality projects testing should be embedded throughout the development process. By doing automatic testing, all from unit tests to acceptance tests, continuously alongside manual testing we ensure that the project always meets its definition of “done”. As the previous chapters mention, this approach is important to ensure robust quality programs and it becomes more important in bigger projects due to cost and time efficiency. 

The success of a project lies in an effective management of assets. Version control systems are an asset of very big importance but of even bigger importance is a good branching strategy. It is crucial to have a balance between the efficiency considerations and the desire for CI. In our project branching has been an important step to work effectively. One group is working with the backend and another with the GUI. What is of big importance while branching for us, and of even more importance in bigger projects, is to merge the branches frequently with the main file.  

Chapter 1 – Covers the importance of adopting techniques of automated build, test and deployment to avoid time consuming and expensive processes to handle errors that could be easier caught in earlier processes and with better documentation.  

Chapter 2 – To be able to do continuous integration, release management and deployment pipelining is essential to have a well working configuration management. 

Chapter 3 - CI is used to transform the default state of an application and be able to do automated testing to always make sure that the application is in a working state.   

Chapter 4 - To ensure high-quality outcomes and the delivery of reliable products it is important to do embedded tests, both manual and automated, through the whole development. 

Chapter 14 - To maintain the integrity of the CI process and ensure smooth software delivery it is important to have an effective management of the version control system and to carefully include branching strategies.

**Comment by sandzan** [comment] 2024-04-24 18:52
To make sure that everyone involved in the project are on the same page and know what is happening to the code it important to test and document everything from the start. This saves time when trying to fix errors since they are caught by the testing and easy to find with the documentation. By automizing this process will save even more time and avoid human errors.  

CI is important to use in a project to be sure that the application is working. Since everyone are working on different parts of the application, issues might occur when trying to merge everything. Especially when it is a big project. CI makes everyone fix the issues before it can be merged to the main program.  

By testing the program regularly, you can save a lot of time. If there is a problem early in the process that isn’t fixed because no testing was made, it might cause even more problems. If testing is done repeatedly, it’s easier to find and fix the problem and will save the project from unnecessary problems caused by it. In bigger project it becomes even more important since it will be hard to know when and where the problem first occurred. 

Branching is a useful thing to use when working on a project. We use it to divide the project in two, backend and GUI. By doing this we can work at the same time and not disturbed the others. To make sure everything works together, we merge the branches to main when new things are added and ready. 

Chapter 1 – It’s important to automate the development, test and release processes to make it faster, cheaper and lower the risk of errors. 

Chapter 2 – Configuration management is required to do continuous integration, release management and deployment pipeline 

Chapter 3 – Continuous integration makes sure default state of the application is working 

Chapter 4 – Testing is important to do frequently through the entire development process to have a high-quality software 

Chapter 14 – Branching comes with a cost and to minimize the risk you should frequently merge it back to the main branch

**Comment by mtaromi** [comment] 2024-05-27 14:25
@Sneakycloud, @sodqv, @ebbabrage, and @sandzan 

Insightful reflections, well done!

**Closed by mtaromi** 2024-05-27 14:25 UTC
